name: Docker Image Creation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
       DOCKER_USER: ${{secrets.DOCKER_USER}}
       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t chinmayapte01/myfirstimage . -f Dockerfile.txt
      
   #- name: Docker Tag
   #   run: docker tag myfirstimage:1.0 imageone:stable
      
    - name: Docker Push
      run: docker push hub.docker.com/repository/docker/chinmayapte01/myfirstimage:1.0
